### ISSUE TITLE
no training set examples for Subject-driven Image Generation in the `toy_data`

### ISSUE THREAD

**Issue by JoshonSmith** [VectorSpaceLab/OmniGen#106]
There are no training set examples for Subject-driven Image Generation in the `toy_data`. 

Can you provide training set examples for Subject-driven Image Generation?

**Comment by staoxiao** [comment]
Hi, @JoshonSmith , here are some examples:
```
{"task_type":"subject","instruction":"A dog <img><|image_1|></img> and a boy <img><|image_2|></img> are running.","input_images":["dog.png", "boy.png"],"output_image":"target.png"}
{"task_type":"subject","instruction":"A dog and a boy are running. The dog is <img><|image_1|></img>, and the boy is <img><|image_2|></img>","input_images":["dog.png", "boy.png"],"output_image":"target.png"}
```

If you just want the model to generate a specific object, like DreamBooth, you can refer to [toy_subject_data](https://github.com/VectorSpaceLab/OmniGen/blob/main/toy_data/toy_subject_data.jsonl) (a example for sks dog)
