### ISSUE TITLE
Feature Request: Add Support for External Paths for Omnigen Models in the LLM Folder in extra_model_paths.yaml

### ISSUE THREAD

**Issue by magimyster** [VectorSpaceLab/OmniGen#127]
I'm not sure if this feature is already supported, but I noticed that Omnigen models in the LLM folder of ComfyUI don't seem to be loaded from external paths, even though other models can be specified in the extra_model_paths.yaml file. It would be very helpful to add support for external paths for Omnigen models in the LLM folder as well. This way, large models could be stored on external drives without needing to modify the internal structure of the ComfyUI folder. Thank you for your attention and consideration.

**Comment by cdmusic2019** [comment]
You can use the 'mklink /d “xxxx” “H:\xxx” ' command in a cmd window to create a virtual connection to the outside drive.

**Comment by magimyster** [comment]
Thank you very much!! I solved it! Sorry, but I'm not very experienced.
