### ISSUE TITLE
Usage instructions are missing

### ISSUE THREAD

**Issue by Eddcapone** [VectorSpaceLab/OmniGen#132]
I installed this tool, but there is no usage instructions. How can I launch it?
We are left in the dark.

PS: The installation instructions are faulty too:
https://stackoverflow.com/questions/77901825/unable-to-activate-environment-conda-prompted-to-run-conda-init-before-cond

**Comment by Eddcapone** [comment]
Nevermind, they are hidden [here ](https://github.com/VectorSpaceLab/OmniGen/issues/132)- I didn't knew what gradio is.

pip install gradio spaces
python app.py

**Comment by staoxiao** [comment]
> Nevermind, they are hidden [here ](https://github.com/VectorSpaceLab/OmniGen/issues/132)- I didn't knew what gradio was.
> 
> ```
> pip install gradio spaces
> python app.py
> ```

You can use the app.py, or follow the examples in [inference.ipynb](https://github.com/VectorSpaceLab/OmniGen/blob/main/inference.ipynb) and [inference_demo.ipynb](https://github.com/VectorSpaceLab/OmniGen/blob/main/inference_demo.ipynb)
