### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Eddcapone** [VectorSpaceLab/OmniGen#133]
I get this error when running the app:

```
python app.py
Fetching 10 files: 100%|##########| 10/10 [00:00<?, ?it/s]
Segmentation fault
(G:\ProgramDataminiconda3homeenvs\omnigen)
```

**Comment by able2608** [comment]
This typically means that there are memory issues on your computer. Perhaps restarting the machine could fix this problem.

**Comment by Eddcapone** [comment]
Yes, I guess there was not enough free space for swapping and not enough RAM. I upgraded my harddisk to a bigger one and now it works.
