### ISSUE TITLE
Inference steps

### ISSUE THREAD

**Issue by temperfugit** [VectorSpaceLab/OmniGen#138]
I see that using 50 inference steps is mentioned in the paper, but I don't see many details about it.  I'm curious if that number was arrived at through testing, or if 50 steps was picked as a reasonable starting value and further testing might find a more optimal number?  My assumption is that in order to converge better on fewer steps it would need to be re-trained or fine tuned with a different noise schedule.

I also don't see any mention of a scheduler.  Can you tell me what scheduler you're using, and is it baked in or could it potentially be swapped for another?

**Comment by staoxiao** [comment]
@temperfugit, to be honest, I haven't tried many different inference step, so I'm not sure what the optimal number is. If you want a very small number of inference steps, like fewer than 10, I think distillation is necessary for the model.

The scheduler is based on the one from SD3, with some modifications to the noise formula. You can refer to it here: https://github.com/VectorSpaceLab/OmniGen/blob/main/OmniGen/scheduler.py#L117. To my knowledge, there isn't an existing scheduler that can replace the current one, but I might have missed something (If there are schedulers that can accelerate SD3, they should be easily adaptable to OmniGen's scheduler).

**Comment by temperfugit** [comment]
Thank you.  I haven't used SD3 yet, I was not aware that it doesn't have swappable schedulers like SDXL does.

OmniGen is a great model that I'm still trying to fully understand.  I'm very grateful for the work you have put into training and releasing it.
