### ISSUE TITLE
Is this model trained from scratch?

### ISSUE THREAD

**Issue by xizaoqu** [VectorSpaceLab/OmniGen#17]
Hi, thanks for presenting this great project. Is this model trained from scratch? Thanks.

**Comment by BitPhinix** [comment]
It's based on phi-3:

<img width="837" alt="Screenshot 2024-10-22 at 6 46 52 PM" src="https://github.com/user-attachments/assets/385bffdf-9003-4fc5-924e-18f7cb61de75">

**Comment by xizaoqu** [comment]
Thanks, sorry I miss it.
