### ISSUE TITLE
Can OmniGen play chess?

### ISSUE THREAD

**Issue by NatanFreeman** [VectorSpaceLab/OmniGen#2]
Can you supply an image of a chess board, say this one for example and have OmniGen play the next move as white? I'm curios as to how good OmniGen's reasoning capabilities are.
![image](https://github.com/user-attachments/assets/34d249b5-c3b0-47cb-9da1-c3c8a872c514)

**Comment by WeiXie-NNU** [comment]
I am new to vision reasoning. Is it possible to play chess using only a foundational vision model?
