### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/root/OmniGen-v1/model.pt'

### ISSUE THREAD

**Issue by mikeyimer** [VectorSpaceLab/OmniGen#37]
When executing the app.py gradio, missing files.

/root/OmniGen/OmniGen/model.py:202: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(os.path.join(model_name, 'model.pt'), map_location='cpu')
Traceback (most recent call last):
  File "/root/OmniGen/app.py", line 13, in <module>
    pipe = OmniGenPipeline.from_pretrained(
  File "/root/OmniGen/OmniGen/pipeline.py", line 79, in from_pretrained
    model = OmniGen.from_pretrained(model_name)
  File "/root/OmniGen/OmniGen/model.py", line 202, in from_pretrained
    ckpt = torch.load(os.path.join(model_name, 'model.pt'), map_location='cpu')
  File "/root/miniconda3/envs/omnigen/lib/python3.10/site-packages/torch/serialization.py", line 1319, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/root/miniconda3/envs/omnigen/lib/python3.10/site-packages/torch/serialization.py", line 659, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/omnigen/lib/python3.10/site-packages/torch/serialization.py", line 640, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/root/OmniGen-v1/model.pt'

**Comment by staoxiao** [comment]
It seems that you didn't download the model successfully. Please make sure you can access the HF hub, and then you can delete the cache file: `/root/OmniGen-v1/` and re-run the script again.

**Comment by mikeyimer** [comment]
> It seems that you didn't download the model successfully. Please make sure you can access the HF hub, and then you can delete the cache file: `/root/OmniGen-v1/` and re-run the script again.

 I changed the model path due to the space,but there is indeed no model.pt files in the HF hub.
![1588](https://github.com/user-attachments/assets/689ea1e6-dbc2-4571-b1e4-59e89ba91be3)
![dfdf](https://github.com/user-attachments/assets/e30e6612-78fd-4e64-b626-a2f20033042f)

**Comment by staoxiao** [comment]
We convert the model.pt into model.safetensors, and the scrip will download the safetensors automatically.

**Comment by litlstereo** [comment]
excuse me please but would anyone would be able to advise where I can find a line to change the .cache/model path folder so it doesn't use c disk's space. Thank you!
