### ISSUE TITLE
Question about versions of Phi-3

### ISSUE THREAD

**Issue by limzh00** [VectorSpaceLab/OmniGen#4]
Greetings. Thanks for your excellent work. 
The paper mentioned you adapt phi-3 architecture as OmniGen backend and you apply phi-3 pretrained weights as initialization. I was not familiar with Phi-3, so I did a little bit research. According to your model scale (3.8B), I infer that you use phi-3-mini, which is pure text LLM, w/o vision reasoning. However, https://arxiv.org/pdf/2404.14219 says it provides phi-3.5-vision, ~4B, which is not that large either. I wonder why you didn't  choose that, just for curiosity.
Thx.

**Comment by staoxiao** [comment]
Thanks for your attention to our work! 
Like other multimodal models, phi3-version includes an LLM and a CLIP. However, we do not wish to introduce too many components and believe that CLIP is not a necessary option for multimodal understanding. Currently, we are using the LLM from phi3-mini-version (without CLIP), but I think using the original phi3-mini LLM would yield similar results.

**Comment by limzh00** [comment]
That's precise response to my concern, thanks.
