### ISSUE TITLE
NameError: name 'is_torch_npu_available' is not defined. Did you mean: 'is_torch_xla_available'?

### ISSUE THREAD

**Issue by larini** [VectorSpaceLab/OmniGen#66]
While running python app.py, I get this error:

Fetching 10 files: 100%|███████████████████████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]
Loading safetensors
Traceback (most recent call last):
  File "C:\git\OmniGen\app.py", line 9, in <module>
    pipe = OmniGenPipeline.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\OmniGen\OmniGen\pipeline.py", line 93, in from_pretrained
    return cls(vae, model, processor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\OmniGen\OmniGen\pipeline.py", line 61, in __init__
    elif is_torch_npu_available():
         ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_torch_npu_available' is not defined. Did you mean: 'is_torch_xla_available'?

**Comment by staoxiao** [comment]
see https://github.com/VectorSpaceLab/OmniGen/issues/67
