### ISSUE TITLE
Patch size used for visual embeddings

### ISSUE THREAD

**Issue by BitPhinix** [VectorSpaceLab/OmniGen#7]
In the paper you mention

> The input to the model can be multimodal interleaved text and images in free form. We utilize the tokenizer of Phi-3 to process text without any modifications. For images, we firstly employ a VAE with a simple linear layer to extract latent representations. Then, they are flattened into a sequence of visual tokens by linearly embedding each patch in the latent space

What patch size did you use for these visual tokens? Did you match `patch_width * patch_height * vae_channels` = `phi3 embedding dim` or did you choose a smaller patch size?

**Comment by staoxiao** [comment]
Hi, @BitPhinix , we use VAE to obtain the latent vector, and set patch-size=2 following DiT

**Comment by BitPhinix** [comment]
Thanks!
